### ISSUE TITLE
更换样例图片后出错

### ISSUE THREAD

**Issue by SteamBoatv** [kiloGrand/License-Plate-Recognition#1]
我在将：inference/images/car.jpg此路径下的图片增加了一个之后，报错如下：
Traceback (most recent call last):
  File "E:\CCPDPyCharm\License-Plate-Recognition-master\main.py", line 252, in <module>
    detect(opt)
  File "E:\CCPDPyCharm\License-Plate-Recognition-master\main.py", line 184, in detect
    s += 'class %s %g个, ' % (names[int(c)-1], n)  # add to string
IndexError: list index out of range

**Comment by kiloGrand** [comment]
模型类别名称names及对应的识别框的颜色colors的list长度只有1
```python
    # Get names and colors
    names = model.module.names if hasattr(model, 'module') else model.names
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in range(len(names))]
```
而yolov5的识别分类多于一种，这是由于训练的过程中，把nc设置称80导致的。
因此在使用yolov5来车牌定位的时候，yolov5的分类结果不一定为1，所以导致int(c)-1大于1，超出names和colors范围。
修改：
```python
                for c in det[:, 5].unique():
                    n = (det[:, 5] == c).sum()  # 统计每个类别的个数
                    if int(c)-1 == 0:  # 0是车牌，yolov5可以识别为广告牌等等，导致这里出错
                        s += 'class %s %g个, ' % (names[int(c)-1], n)  # add to string


                    if save_img or view_img:  # 所有的yolov5识别结果都用同一种颜色color[0]来框住
                        im0 = plot_one_box(xyxy, im0, label=label, color=colors[0], line_thickness=3)
```
