### ISSUE TITLE
请问LPRNet训练时候加了log_softmax，为什么测试时候不加呢？

### ISSUE THREAD

**Issue by Ryuk17** [kiloGrand/License-Plate-Recognition#2]
训练：https://github.com/kiloGrand/License-Plate-Recognition/blob/1f06dd82be7258933a609634debd7366867a8e9f/LPRNet/train_LPRNet.py#L181
测试：https://github.com/kiloGrand/License-Plate-Recognition/blob/1f06dd82be7258933a609634debd7366867a8e9f/LPRNet/test_LPRNet.py#L104

**Comment by kiloGrand** [comment]
LPRNet在训练时加入了log_softmax是为了优化模型的训练过程，使得损失函数更容易优化。而在测试时，我们需要得到模型最终的输出结果并直接用于greedy decode，因此不需要加入log_softmax。
